# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def shared_pods

  # pod for mono
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core', 'RCTImage', 'cxxreact', 'CxxBridge', 'RCTWebSocket', 'DevSupport',
    'RCTAnimation', 'RCTText', 'RCTLinkingIOS'
  ]
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # This should already be auto-added for you, if not add the line below
  pod 'Firebase/Core', '~> 5.20.0'
  pod 'Firebase/Auth', '~> 5.20.0'
  pod 'Firebase/Firestore', '~> 5.20.0'
  pod 'Firebase/Storage', '~> 5.20.0'
  pod 'Firebase/Messaging', '~> 5.20.0'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
end

target 'mono' do
  shared_pods

  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

end

target 'monoTests' do
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-places'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    #if target.name == "React"
    #  target.remove_from_project
    #end
  end
end
